services:
  frontend:
    hostname: dockeranium-web
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "${FRONTEND_PORT:-3003}:${FRONTEND_INTERNAL_PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${FRONTEND_INTERNAL_PORT:-3000}
    env_file:
      - .env.prod
    restart: unless-stopped
    command: npm run start
    depends_on:
      - backend

  backend:
    hostname: dockeranium-api
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.prod
    restart: unless-stopped

networks:
  default:
    name: dockeranium-network-prod
